language: node_js
node_js:
  - "10"

cache:
  directories:
  - node_modules

before_script:
  - export NODE_OPTIONS=--max_old_space_size=4096
  - npm install

script:
  - npm run lint-contracts
  - npm run test-js

after_script:
  - npm run coverage
  - cat coverage/lcov.info | coveralls