live:
  - name: RSK Mainnet
    networks:
      - name: Mainnet
        chainid: 30
        id: rsk-mainnet
        host: wws://mainnet.sovryn.app/websocket

      - name: Testnet
        chainid: 31
        id: rsk-testnet
        host: https://testnet.sovryn.app/rpc
